/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Config.h"

void USART3_IRQHandler(void)
{
	if ( (USART3->SR & RIF) )
	{
		char ptrDataReceive = USART3->DR;

		switch (ptrDataReceive)
		{
			case 'I':
				Usart_Transmit("\nRecibi una I.\r\n Voy a transmitir con interrupcion.\r\n\n", 1);
				return;
			case 'D':
				Usart_Transmit("\nRecibi una D.\r\n Voy a transmitir una cadena enorme por Direct Memory Access (DMA).\r\n Hay dudas al respecto?\r\n\n\t\t No tengan miedo de preguntar...\r\n\n", 2);
				return;
			case 'S':
				Usart_Transmit("\nRecibi una S y mando por DMA.\r\n\n", 2);
				return;
			default:
				return;
		}

	}else if( (USART3->SR & TIF) && (*ptrDataTransmit_Int == '\0') )
	{
		USART3->CR1	&= ~USART_CR1_TXEIE;
		ptrDataTransmit_Int = (void *)0;
		return;

	}else if( (USART3->SR & TIF) && (*ptrDataTransmit_Int != '\0') ) USART3->DR = *ptrDataTransmit_Int++;

}

void DMA1_Stream3_IRQHandler()
{
	DMA1->LIFCR |= DMA_LIFCR_CTCIF3;
	USART3->CR3 &= ~USART_CR3_DMAT;

}

int main(void)
{
	ConfigClock();
	UsartConfig();

	Usart_Transmit("\nVoy a enviar por poleo.\r\n\n", 0);

	for(;;);
}
